import { Download, Eye } from "lucide-react";
import { Table, TBody, TD, TH, THead, TR } from "@/components/ui/Table";

export type Report = {
  id: string;
  title: string;
  type: string;
  generatedBy: string;
  createdAt: Date;
  status: string;
  url: string;
};

type EmployeeRecentReportTableProps = {
  reports?: Report[];
};

const defaultReports: Report[] = [
  {
    id: "1",
    title: "Q1 Talent Retention Analysis",
    type: "Turnover",
    generatedBy: "Sarah Connor",
    createdAt: new Date("2026-06-15"),
    status: "Completed",
    url: "#",
  },
  {
    id: "2",
    title: "Weekly Team Productivity Summary",
    type: "Performance",
    generatedBy: "Alicia Turner",
    createdAt: new Date("2026-06-12"),
    status: "Completed",
    url: "#",
  },
  {
    id: "3",
    title: "Payroll Variance Report",
    type: "Payroll",
    generatedBy: "Mike Jordan",
    createdAt: new Date("2026-06-10"),
    status: "Pending",
    url: "#",
  },
];

export default function EmployeeRecentReportTable({
  reports = defaultReports,
}: EmployeeRecentReportTableProps) {
  const visibleReports = reports.slice(0, 3);

  if (visibleReports.length === 0) {
    return (
      <div className="flex min-h-45 items-center justify-center rounded-2xl border border-dashed border-slate-200 bg-slate-50 px-4 text-center text-sm text-secondary">
        No reports available yet.
      </div>
    );
  }

  return (
    <div className="overflow-x-auto">
      <Table className="min-w-190">
        <THead>
          <TR>
            <TH className="text-left text-primary">Report Name</TH>
            <TH className="text-left text-primary">Type</TH>
            <TH className="text-left text-primary">Generated By</TH>
            <TH className="text-left text-primary">Date</TH>
            <TH className="text-left text-primary">Status</TH>
            <TH className="text-right text-primary">Actions</TH>
          </TR>
        </THead>

        <TBody>
          {visibleReports.map((report) => (
            <TR key={report.id}>
              <TD className="font-medium text-primary">{report.title}</TD>
              <TD className="text-secondary">{report.type}</TD>
              <TD className="text-secondary">{report.generatedBy}</TD>
              <TD className="text-secondary">
                {new Date(report.createdAt).toLocaleDateString("en-US", {
                  month: "short",
                  day: "numeric",
                  year: "numeric",
                })}
              </TD>
              <TD>
                <span
                  className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${
                    report.status === "Completed"
                      ? "bg-emerald-100 text-emerald-700"
                      : report.status === "In Progress"
                        ? "bg-amber-100 text-amber-700"
                        : "bg-slate-100 text-slate-700"
                  }`}
                >
                  {report.status}
                </span>
              </TD>
              <TD className="text-right">
                <div className="flex items-center justify-end gap-2">
                  <a
                    href={report.url}
                    aria-label={`Download ${report.title}`}
                    className="rounded-md p-1.5 text-secondary transition-colors hover:bg-slate-100 hover:text-primary"
                  >
                    <Download size={16} />
                  </a>
                  <a
                    href={report.url}
                    aria-label={`View ${report.title}`}
                    className="rounded-md p-1.5 text-secondary transition-colors hover:bg-slate-100 hover:text-primary"
                  >
                    <Eye size={16} />
                  </a>
                </div>
              </TD>
            </TR>
          ))}
        </TBody>
      </Table>
    </div>
  );
}
